import type { User, Choir, ChoirMember, Event, Contribution, Expense, MusicFile } from '@/types/database.types';
import type { MemberWithUser, DashboardStats, FinanceSummary } from '@/types/app.types';

// Simulate network delay
export const delay = (ms = 400) => new Promise(res => setTimeout(res, ms + Math.random() * 300));

// Current user (logged in)
export const mockCurrentUser: User = {
  id: 'usr_001',
  phone: '+255712345678',
  phone_verified_at: '2024-01-15T10:00:00Z',
  email: 'amina.saleh@example.com',
  full_name: 'Amina Saleh',
  display_name: 'Amina',
  photo_url: null,
  date_of_birth: '1990-05-15',
  gender: 'female',
  preferred_language: 'sw',
  low_data_mode: false,
  biometric_enabled: false,
  failed_login_attempts: 0,
  locked_until: null,
  last_login_at: new Date().toISOString(),
  last_login_ip: '192.168.1.1',
  is_super_admin: false,
  created_at: '2024-01-15T10:00:00Z',
  updated_at: new Date().toISOString(),
  deleted_at: null,
  deleted_by: null,
};

// Current choir
export const mockChoir: Choir = {
  id: 'chr_001',
  name: 'Kwaya ya Moyo Mtakatifu',
  parish: "St. Joseph's Parish",
  diocese: 'Archdiocese of Dar es Salaam',
  region: 'Dar es Salaam',
  country: 'TZ',
  logo_url: null,
  description: 'Catholic choir serving the community since 1985',
  founded_year: 1985,
  monthly_dues_amount: 5000,
  dues_currency: 'TZS',
  settings: {},
  created_at: '2020-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  deleted_at: null,
};

// Mock users
const mockUsers: User[] = [
  mockCurrentUser,
  {
    ...mockCurrentUser,
    id: 'usr_002',
    phone: '+255713456789',
    full_name: 'John Mwamba',
    display_name: 'John',
    gender: 'male',
    preferred_language: 'en',
  },
  {
    ...mockCurrentUser,
    id: 'usr_003',
    phone: '+255714567890',
    full_name: 'Grace Kimaro',
    display_name: 'Grace',
    gender: 'female',
  },
  {
    ...mockCurrentUser,
    id: 'usr_004',
    phone: '+255715678901',
    full_name: 'Peter Mushi',
    display_name: 'Peter',
    gender: 'male',
  },
  {
    ...mockCurrentUser,
    id: 'usr_005',
    phone: '+255716789012',
    full_name: 'Mary Ndosi',
    display_name: 'Mary',
    gender: 'female',
  },
  {
    ...mockCurrentUser,
    id: 'usr_006',
    phone: '+255717890123',
    full_name: 'David Shayo',
    display_name: 'David',
    gender: 'male',
  },
  {
    ...mockCurrentUser,
    id: 'usr_007',
    phone: '+255718901234',
    full_name: 'Sarah Mwakyusa',
    display_name: 'Sarah',
    gender: 'female',
  },
  {
    ...mockCurrentUser,
    id: 'usr_008',
    phone: '+255719012345',
    full_name: 'Joseph Lyimo',
    display_name: 'Joseph',
    gender: 'male',
  },
  {
    ...mockCurrentUser,
    id: 'usr_009',
    phone: '+255710123456',
    full_name: 'Anna Kessy',
    display_name: 'Anna',
    gender: 'female',
  },
  {
    ...mockCurrentUser,
    id: 'usr_010',
    phone: '+255711234567',
    full_name: 'Michael Tenga',
    display_name: 'Michael',
    gender: 'male',
  },
  {
    ...mockCurrentUser,
    id: 'usr_011',
    phone: '+255712345670',
    full_name: 'Elizabeth Mwakasege',
    display_name: 'Elizabeth',
    gender: 'female',
  },
  {
    ...mockCurrentUser,
    id: 'usr_012',
    phone: '+255713456780',
    full_name: 'Thomas Mwangosi',
    display_name: 'Thomas',
    gender: 'male',
  },
];

// Mock choir members
export const mockChoirMembers: ChoirMember[] = [
  {
    id: 'mem_001',
    choir_id: 'chr_001',
    user_id: 'usr_001',
    role: 'choir_leader',
    voice_part: 'soprano',
    status: 'active',
    joined_at: '2020-01-15',
    notes: null,
    created_at: '2020-01-15T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_002',
    choir_id: 'chr_001',
    user_id: 'usr_002',
    role: 'assistant_leader',
    voice_part: 'tenor',
    status: 'active',
    joined_at: '2020-03-10',
    notes: null,
    created_at: '2020-03-10T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_003',
    choir_id: 'chr_001',
    user_id: 'usr_003',
    role: 'secretary',
    voice_part: 'alto',
    status: 'active',
    joined_at: '2020-02-20',
    notes: null,
    created_at: '2020-02-20T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_004',
    choir_id: 'chr_001',
    user_id: 'usr_004',
    role: 'treasurer',
    voice_part: 'bass',
    status: 'active',
    joined_at: '2020-04-05',
    notes: null,
    created_at: '2020-04-05T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_005',
    choir_id: 'chr_001',
    user_id: 'usr_005',
    role: 'music_teacher',
    voice_part: 'soprano',
    status: 'active',
    joined_at: '2021-01-10',
    notes: null,
    created_at: '2021-01-10T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_006',
    choir_id: 'chr_001',
    user_id: 'usr_006',
    role: 'member',
    voice_part: 'tenor',
    status: 'active',
    joined_at: '2021-06-15',
    notes: null,
    created_at: '2021-06-15T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_007',
    choir_id: 'chr_001',
    user_id: 'usr_007',
    role: 'member',
    voice_part: 'alto',
    status: 'active',
    joined_at: '2022-01-20',
    notes: null,
    created_at: '2022-01-20T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_008',
    choir_id: 'chr_001',
    user_id: 'usr_008',
    role: 'member',
    voice_part: 'bass',
    status: 'probation',
    joined_at: '2024-01-05',
    notes: 'New member, learning the repertoire',
    created_at: '2024-01-05T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_009',
    choir_id: 'chr_001',
    user_id: 'usr_009',
    role: 'member',
    voice_part: 'alto',
    status: 'active',
    joined_at: '2023-03-12',
    notes: null,
    created_at: '2023-03-12T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_010',
    choir_id: 'chr_001',
    user_id: 'usr_010',
    role: 'member',
    voice_part: 'bass',
    status: 'active',
    joined_at: '2022-08-30',
    notes: null,
    created_at: '2022-08-30T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_011',
    choir_id: 'chr_001',
    user_id: 'usr_011',
    role: 'member',
    voice_part: 'soprano',
    status: 'inactive',
    joined_at: '2021-02-14',
    notes: 'On maternity leave',
    created_at: '2021-02-14T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mem_012',
    choir_id: 'chr_001',
    user_id: 'usr_012',
    role: 'member',
    voice_part: 'tenor',
    status: 'probation',
    joined_at: '2024-02-01',
    notes: null,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
];

// Combined member with user data
export const mockMembersWithUsers: MemberWithUser[] = mockChoirMembers.map((member) => ({
  ...member,
  user: mockUsers.find((u) => u.id === member.user_id)!,
}));

// Current member (logged in user's membership)
export const mockCurrentMember = mockChoirMembers.find((m) => m.user_id === mockCurrentUser.id)!;

// Mock events
const today = new Date();
const getDateOffset = (days: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

export const mockEvents: Event[] = [
  {
    id: 'evt_001',
    choir_id: 'chr_001',
    title: 'Mazoezi ya Jumapili',
    description: 'Weekly Sunday rehearsal',
    event_type: 'rehearsal',
    location: "St. Joseph's Parish Hall",
    starts_at: getDateOffset(2),
    ends_at: getDateOffset(2),
    reminder_sent_24h: false,
    reminder_sent_2h: false,
    created_by: 'usr_001',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'evt_002',
    choir_id: 'chr_001',
    title: 'Misa ya Jumapili',
    description: 'Sunday Mass service',
    event_type: 'mass',
    location: "St. Joseph's Cathedral",
    starts_at: getDateOffset(3),
    ends_at: getDateOffset(3),
    reminder_sent_24h: false,
    reminder_sent_2h: false,
    created_by: 'usr_001',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'evt_003',
    choir_id: 'chr_001',
    title: 'Harusi - Familia ya Mushi',
    description: 'Wedding ceremony for Mushi family',
    event_type: 'wedding',
    location: 'Holy Spirit Church, Mikocheni',
    starts_at: getDateOffset(7),
    ends_at: getDateOffset(7),
    reminder_sent_24h: false,
    reminder_sent_2h: false,
    created_by: 'usr_001',
    created_at: '2024-01-10T00:00:00Z',
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'evt_004',
    choir_id: 'chr_001',
    title: 'Mkutano wa Kamati',
    description: 'Monthly committee meeting',
    event_type: 'meeting',
    location: 'Parish Office',
    starts_at: getDateOffset(5),
    ends_at: getDateOffset(5),
    reminder_sent_24h: false,
    reminder_sent_2h: false,
    created_by: 'usr_001',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'evt_005',
    choir_id: 'chr_001',
    title: 'Tamasha la Pasaka',
    description: 'Easter concert',
    event_type: 'concert',
    location: 'Dar es Salaam Cultural Center',
    starts_at: getDateOffset(14),
    ends_at: getDateOffset(14),
    reminder_sent_24h: false,
    reminder_sent_2h: false,
    created_by: 'usr_001',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
];

// Mock contributions
export const mockContributions: Contribution[] = [
  {
    id: 'con_001',
    choir_id: 'chr_001',
    member_id: 'mem_001',
    amount: 5000,
    currency: 'TZS',
    category: 'monthly_dues',
    contribution_date: '2024-02-01',
    receipt_url: null,
    note: 'February dues',
    recorded_by: 'usr_004',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
    deleted_at: null,
    deleted_by: null,
  },
  {
    id: 'con_002',
    choir_id: 'chr_001',
    member_id: 'mem_002',
    amount: 5000,
    currency: 'TZS',
    category: 'monthly_dues',
    contribution_date: '2024-02-01',
    receipt_url: null,
    note: 'February dues',
    recorded_by: 'usr_004',
    created_at: '2024-02-01T10:30:00Z',
    updated_at: '2024-02-01T10:30:00Z',
    deleted_at: null,
    deleted_by: null,
  },
  {
    id: 'con_003',
    choir_id: 'chr_001',
    member_id: 'mem_003',
    amount: 10000,
    currency: 'TZS',
    category: 'fundraiser',
    contribution_date: '2024-02-10',
    receipt_url: null,
    note: 'Easter concert fundraiser',
    recorded_by: 'usr_004',
    created_at: '2024-02-10T14:00:00Z',
    updated_at: '2024-02-10T14:00:00Z',
    deleted_at: null,
    deleted_by: null,
  },
  {
    id: 'con_004',
    choir_id: 'chr_001',
    member_id: 'mem_004',
    amount: 5000,
    currency: 'TZS',
    category: 'monthly_dues',
    contribution_date: '2024-02-05',
    receipt_url: null,
    note: null,
    recorded_by: 'usr_004',
    created_at: '2024-02-05T09:00:00Z',
    updated_at: '2024-02-05T09:00:00Z',
    deleted_at: null,
    deleted_by: null,
  },
  {
    id: 'con_005',
    choir_id: 'chr_001',
    member_id: 'mem_005',
    amount: 25000,
    currency: 'TZS',
    category: 'special',
    contribution_date: '2024-02-15',
    receipt_url: null,
    note: 'Uniform contribution',
    recorded_by: 'usr_004',
    created_at: '2024-02-15T11:00:00Z',
    updated_at: '2024-02-15T11:00:00Z',
    deleted_at: null,
    deleted_by: null,
  },
];

// Mock expenses
export const mockExpenses: Expense[] = [
  {
    id: 'exp_001',
    choir_id: 'chr_001',
    amount: 15000,
    currency: 'TZS',
    category: 'transport',
    expense_date: '2024-02-03',
    description: 'Bus fare for wedding performance',
    receipt_url: null,
    recorded_by: 'usr_004',
    created_at: '2024-02-03T16:00:00Z',
    updated_at: '2024-02-03T16:00:00Z',
    deleted_at: null,
    deleted_by: null,
  },
  {
    id: 'exp_002',
    choir_id: 'chr_001',
    amount: 8000,
    currency: 'TZS',
    category: 'materials',
    expense_date: '2024-02-08',
    description: 'Printing music sheets',
    receipt_url: null,
    recorded_by: 'usr_004',
    created_at: '2024-02-08T10:00:00Z',
    updated_at: '2024-02-08T10:00:00Z',
    deleted_at: null,
    deleted_by: null,
  },
  {
    id: 'exp_003',
    choir_id: 'chr_001',
    amount: 12000,
    currency: 'TZS',
    category: 'meals',
    expense_date: '2024-02-14',
    description: 'Refreshments for committee meeting',
    receipt_url: null,
    recorded_by: 'usr_004',
    created_at: '2024-02-14T15:00:00Z',
    updated_at: '2024-02-14T15:00:00Z',
    deleted_at: null,
    deleted_by: null,
  },
];

// Mock music files
export const mockMusicFiles: MusicFile[] = [
  {
    id: 'mus_001',
    choir_id: 'chr_001',
    title: 'Bwana Yesu Asifiwe',
    composer: 'Traditional',
    file_type: 'pdf',
    file_url: '/music/bwana-yesu.pdf',
    file_size_bytes: 256000,
    voice_parts: ['soprano', 'alto', 'tenor', 'bass'],
    category: 'Hymn',
    liturgical_season: 'Ordinary Time',
    copyright_confirmed: true,
    copyright_confirmed_by: 'usr_001',
    copyright_confirmed_at: '2024-01-01T00:00:00Z',
    uploaded_by: 'usr_005',
    uploaded_at: '2024-01-15T00:00:00Z',
    created_at: '2024-01-15T00:00:00Z',
    deleted_at: null,
  },
  {
    id: 'mus_002',
    choir_id: 'chr_001',
    title: 'Hosana kwa Mwana wa Daudi',
    composer: 'Fr. Stephen Mbunga',
    file_type: 'pdf',
    file_url: '/music/hosana.pdf',
    file_size_bytes: 180000,
    voice_parts: ['soprano', 'alto', 'tenor', 'bass'],
    category: 'Mass',
    liturgical_season: 'Lent',
    copyright_confirmed: true,
    copyright_confirmed_by: 'usr_001',
    copyright_confirmed_at: '2024-01-10T00:00:00Z',
    uploaded_by: 'usr_005',
    uploaded_at: '2024-01-20T00:00:00Z',
    created_at: '2024-01-20T00:00:00Z',
    deleted_at: null,
  },
  {
    id: 'mus_003',
    choir_id: 'chr_001',
    title: 'Alleluia - Easter',
    composer: 'Traditional',
    file_type: 'mp3',
    file_url: '/music/alleluia-easter.mp3',
    file_size_bytes: 3500000,
    voice_parts: ['soprano', 'alto', 'tenor', 'bass'],
    category: 'Hymn',
    liturgical_season: 'Easter',
    copyright_confirmed: true,
    copyright_confirmed_by: 'usr_001',
    copyright_confirmed_at: '2024-02-01T00:00:00Z',
    uploaded_by: 'usr_005',
    uploaded_at: '2024-02-01T00:00:00Z',
    created_at: '2024-02-01T00:00:00Z',
    deleted_at: null,
  },
];

// Computed stats
export const mockDashboardStats: DashboardStats = {
  totalMembers: mockChoirMembers.length,
  activeMembers: mockChoirMembers.filter((m) => m.status === 'active').length,
  upcomingEvents: mockEvents.filter((e) => new Date(e.starts_at) > new Date()).slice(0, 3),
  recentContributions: mockContributions.reduce((sum, c) => sum + c.amount, 0),
  attendanceRate: 85,
};

export const mockFinanceSummary: FinanceSummary = {
  totalContributions: mockContributions.reduce((sum, c) => sum + c.amount, 0),
  totalExpenses: mockExpenses.reduce((sum, e) => sum + e.amount, 0),
  balance:
    mockContributions.reduce((sum, c) => sum + c.amount, 0) -
    mockExpenses.reduce((sum, e) => sum + e.amount, 0),
  currency: 'TZS',
  period: {
    start: '2024-02-01',
    end: '2024-02-29',
  },
  contributionsByCategory: {
    monthly_dues: 15000,
    fundraiser: 10000,
    special: 25000,
  },
  expensesByCategory: {
    transport: 15000,
    materials: 8000,
    meals: 12000,
  },
};
